Repository DDakDaegi/DDakDaegi, pull requests merged in 2025-03, with the labels that each got.

#5 Spring Security 에 필요한 기초적인 Jwt, 필터 추가
  src/main/java/com/example/ddakdaegi/global/common/dto/AuthUser.java
  src/main/java/com/example/ddakdaegi/global/common/exception/enums/ErrorCode.java
  src/main/java/com/example/ddakdaegi/global/config/security/JwtAuthenticationToken.java
  src/main/java/com/example/ddakdaegi/global/config/security/SecurityConfig.java
  src/main/java/com/example/ddakdaegi/global/filter/JwtExceptionFilter.java
  src/main/java/com/example/ddakdaegi/global/filter/JwtFilter.java
  src/main/java/com/example/ddakdaegi/global/util/CookieUtil.java
  src/main/java/com/example/ddakdaegi/global/util/jwt/JwtConstants.java
  src/main/java/com/example/ddakdaegi/global/util/jwt/JwtProvider.java
Labels: ✨ feat

#7 Member 회원가입, 로그인 API 구현
  src/main/java/com/example/ddakdaegi/domain/auth/controller/AuthController.java
  src/main/java/com/example/ddakdaegi/domain/auth/dto/request/LoginRequest.java
  src/main/java/com/example/ddakdaegi/domain/auth/dto/request/RegisterRequest.java
  src/main/java/com/example/ddakdaegi/domain/auth/dto/response/TokenDto.java
  src/main/java/com/example/ddakdaegi/domain/auth/service/AuthService.java
  src/main/java/com/example/ddakdaegi/domain/member/entity/Member.java
  src/main/java/com/example/ddakdaegi/domain/member/repository/MemberRepository.java
  src/main/java/com/example/ddakdaegi/global/filter/JwtFilter.java
  src/main/java/com/example/ddakdaegi/global/util/jwt/JwtConstants.java
  src/main/java/com/example/ddakdaegi/global/util/jwt/JwtProvider.java
Labels: 🐛 bug, ✨ feat

#13 Product 상품 등록 조회 기본 api 기능 구현
  src/main/java/com/example/ddakdaegi/domain/product/controller/ProductController.java
  src/main/java/com/example/ddakdaegi/domain/product/dto/request/ProductRequest.java
  src/main/java/com/example/ddakdaegi/domain/product/dto/response/ProductResponse.java
  src/main/java/com/example/ddakdaegi/domain/product/entity/Product.java
  src/main/java/com/example/ddakdaegi/domain/product/repository/ProductRepository.java
  src/main/java/com/example/ddakdaegi/domain/product/service/ProductService.java
  src/main/resources/application-local.properties
Labels: ✨ feat

#16 Feat: 주문 생성 API 구현
  .gitignore
  build.gradle
  src/main/java/com/example/ddakdaegi/DdakdaegiApplication.java
  src/main/java/com/example/ddakdaegi/domain/order/controller/OrderController.java
  src/main/java/com/example/ddakdaegi/domain/order/dto/request/CreateOrderRequest.java
  src/main/java/com/example/ddakdaegi/domain/order/dto/request/PromotionProductDto.java
  src/main/java/com/example/ddakdaegi/domain/order/dto/response/OrderPromotionProductDto.java
  src/main/java/com/example/ddakdaegi/domain/order/dto/response/OrderResponse.java
  src/main/java/com/example/ddakdaegi/domain/order/entity/Order.java
  src/main/java/com/example/ddakdaegi/domain/order/entity/OrderPromotionProduct.java
  src/main/java/com/example/ddakdaegi/domain/order/repository/OrderPromotionProductRepository.java
  src/main/java/com/example/ddakdaegi/domain/order/repository/OrderRepository.java
  src/main/java/com/example/ddakdaegi/domain/order/service/OrderService.java
  src/main/java/com/example/ddakdaegi/domain/promotion/entity/PromotionProduct.java
  src/main/java/com/example/ddakdaegi/domain/promotion/repository/PromotionProductRepository.java
  src/test/java/com/example/ddakdaegi/domain/order/service/OrderServiceTest.java
Labels: ✨ feat

#22 Feat: 주문 단건 & 페이징 목록 조회 구현
  src/main/java/com/example/ddakdaegi/domain/image/ImageRepository.java
  src/main/java/com/example/ddakdaegi/domain/image/entity/Image.java
  src/main/java/com/example/ddakdaegi/domain/order/controller/OrderController.java
  src/main/java/com/example/ddakdaegi/domain/order/dto/request/CreateOrderRequest.java
  src/main/java/com/example/ddakdaegi/domain/order/dto/request/PromotionProductRequest.java
  src/main/java/com/example/ddakdaegi/domain/order/dto/response/OrderDetailResponse.java
  src/main/java/com/example/ddakdaegi/domain/order/dto/response/OrderPromotionProductDto.java
  src/main/java/com/example/ddakdaegi/domain/order/dto/response/OrderResponse.java
  src/main/java/com/example/ddakdaegi/domain/order/repository/OrderPromotionProductRepository.java
  src/main/java/com/example/ddakdaegi/domain/order/repository/OrderRepository.java
  src/main/java/com/example/ddakdaegi/domain/order/repository/OrderRepositoryCustom.java
  src/main/java/com/example/ddakdaegi/domain/order/repository/OrderRepositoryCustomImpl.java
  src/main/java/com/example/ddakdaegi/domain/order/service/OrderService.java
  src/main/java/com/example/ddakdaegi/domain/promotion/dto/response/PromotionProductDto.java
  src/test/java/com/example/ddakdaegi/domain/order/service/OrderServiceTest.java
Labels: ✨ feat

#24 Feat: 주문 취소 구현
  src/main/java/com/example/ddakdaegi/domain/order/controller/OrderController.java
  src/main/java/com/example/ddakdaegi/domain/order/entity/Order.java
  src/main/java/com/example/ddakdaegi/domain/order/service/OrderService.java
  src/main/java/com/example/ddakdaegi/domain/product/entity/Product.java
  src/main/java/com/example/ddakdaegi/domain/promotion/entity/PromotionProduct.java
Labels: ✨ feat

#26 이미지 기능 추가
  src/main/java/com/example/ddakdaegi/domain/image/controller/ImageController.java
  src/main/java/com/example/ddakdaegi/domain/image/dto/response/ImageResponse.java
  src/main/java/com/example/ddakdaegi/domain/image/entity/Image.java
  src/main/java/com/example/ddakdaegi/domain/image/repository/ImageRepository.java
  src/main/java/com/example/ddakdaegi/domain/image/service/ImageService.java
  src/main/java/com/example/ddakdaegi/domain/image/service/S3ImageService.java
  src/main/java/com/example/ddakdaegi/global/common/exception/enums/ErrorCode.java
  src/main/java/com/example/ddakdaegi/global/config/aws/S3Config.java
  src/test/java/com/example/ddakdaegi/domain/order/service/OrderServiceTest.java
Labels: ✨ feat

#29 Feat/product
  src/main/java/com/example/ddakdaegi/domain/product/controller/ProductController.java
  src/main/java/com/example/ddakdaegi/domain/product/dto/request/ProductRequest.java
  src/main/java/com/example/ddakdaegi/domain/product/dto/request/ProductSoldOutSetRequest.java
  src/main/java/com/example/ddakdaegi/domain/product/dto/response/ProductResponse.java
  src/main/java/com/example/ddakdaegi/domain/product/entity/Product.java
  src/main/java/com/example/ddakdaegi/domain/product/repository/ProductRepository.java
  src/main/java/com/example/ddakdaegi/domain/product/service/ProductService.java
  src/main/java/com/example/ddakdaegi/global/common/exception/enums/ErrorCode.java
Labels: ✨ feat

#32 Refactor: 동시성 제어 - DB Lock
  src/main/java/com/example/ddakdaegi/domain/order/controller/OrderController.java
  src/main/java/com/example/ddakdaegi/domain/order/dto/request/CreateOrderRequest.java
  src/main/java/com/example/ddakdaegi/domain/order/dto/response/OrderPromotionProductDto.java
  src/main/java/com/example/ddakdaegi/domain/order/dto/response/OrderResponse.java
  src/main/java/com/example/ddakdaegi/domain/order/repository/OrderRepositoryCustomImpl.java
  src/main/java/com/example/ddakdaegi/domain/order/service/StockService.java
  src/main/java/com/example/ddakdaegi/domain/promotion/repository/PromotionProductRepository.java
Labels: 🔄 refactor

#34 Feat/product
  src/main/java/com/example/ddakdaegi/domain/product/dto/response/ProductResponse.java
  src/main/java/com/example/ddakdaegi/domain/product/service/ProductService.java
  src/test/java/com/example/ddakdaegi/domain/product/service/ProductServiceTest.java
Labels: 🐛 bug

#37 Refactor: 동시성 제어 - Redis Lock
  src/main/java/com/example/ddakdaegi/domain/order/controller/OrderController.java
  src/main/java/com/example/ddakdaegi/domain/order/dto/request/CreateOrderRequest.java
  src/main/java/com/example/ddakdaegi/domain/order/service/OrderService.java
  src/main/java/com/example/ddakdaegi/domain/order/service/StockService.java
  src/main/java/com/example/ddakdaegi/domain/promotion/repository/PromotionProductRepository.java
  src/main/java/com/example/ddakdaegi/domain/promotion/repository/PromotionRepository.java
  src/main/java/com/example/ddakdaegi/global/common/exception/enums/ErrorCode.java
  src/main/java/com/example/ddakdaegi/global/util/lock/LettuceLockStockFacade.java
  src/main/java/com/example/ddakdaegi/global/util/lock/RedisLockRepository.java
Labels: 🔄 refactor

#38 Refactor: 동시성 제어 - Redis Lock
  src/main/java/com/example/ddakdaegi/domain/order/controller/OrderController.java
  src/main/java/com/example/ddakdaegi/global/common/exception/enums/ErrorCode.java
  src/main/java/com/example/ddakdaegi/global/util/lock/RedissonLockStockFacade.java
  src/test/java/com/example/ddakdaegi/domain/order/service/ConcurrencyStockServiceTest.java
  src/test/java/com/example/ddakdaegi/global/util/lock/LettuceLockStockFacadeTest.java
  src/test/java/com/example/ddakdaegi/global/util/lock/RedissonLockStockFacadeTest.java
Labels: 🔄 refactor

#39 Refactor: 동시성 제어 - AOP 방식으로 Redis Lock 적용
  src/main/java/com/example/ddakdaegi/domain/order/controller/OrderController.java
  src/main/java/com/example/ddakdaegi/domain/order/service/StockService.java
  src/main/java/com/example/ddakdaegi/global/common/annotation/Locked.java
  src/main/java/com/example/ddakdaegi/global/common/aspect/StockLockAspect.java
  src/main/java/com/example/ddakdaegi/global/util/lock/RedisLockRepository.java
  src/test/java/com/example/ddakdaegi/domain/order/service/ConcurrencyStockServiceTest.java
  src/test/java/com/example/ddakdaegi/global/util/lock/LettuceLockStockFacadeTest.java
  src/test/java/com/example/ddakdaegi/global/util/lock/RedissonLockStockFacadeTest.java
Labels: 🔄 refactor

#42 Refactor: AOP 로직 수정
  src/main/java/com/example/ddakdaegi/domain/order/service/StockService.java
  src/main/java/com/example/ddakdaegi/global/common/annotation/Locked.java
  src/main/java/com/example/ddakdaegi/global/common/annotation/RedissonLocked.java
  src/main/java/com/example/ddakdaegi/global/common/aspect/StockLockAspect.java
  src/test/java/com/example/ddakdaegi/domain/order/service/ConcurrencyStockServiceTest.java
Labels: 🔄 refactor

#43 Test: OrderServiceTest 서비스 테스트 코드 작성
  src/test/java/com/example/ddakdaegi/domain/order/service/OrderServiceTest.java
Labels: 🧪 test

#47 Test: StockServiceTest 서비스 테스트 코드 작성
  src/test/java/com/example/ddakdaegi/domain/order/service/OrderServiceTest.java
  src/test/java/com/example/ddakdaegi/domain/order/service/StockServiceTest.java
Labels: 🧪 test

#51 Fix : Auth, Member Controller입력값 검증 추가
  src/main/java/com/example/ddakdaegi/domain/auth/controller/AuthController.java
  src/main/java/com/example/ddakdaegi/domain/auth/dto/request/RegisterRequest.java
  src/main/java/com/example/ddakdaegi/domain/member/controller/AdminMemberController.java
  src/main/java/com/example/ddakdaegi/domain/member/controller/MemberController.java
  src/main/java/com/example/ddakdaegi/domain/member/dto/request/MemberUpdatePasswordRequest.java
  src/main/java/com/example/ddakdaegi/domain/member/dto/request/MemberUpdateRequest.java
  src/main/java/com/example/ddakdaegi/domain/member/dto/request/MemberUpdateRoleRequest.java
Labels: 🔄 refactor

#50 Infra : CI / 코드커버리지 검사 추가
  .github/workflows/integration.yml
  build.gradle
  src/main/java/com/example/ddakdaegi/domain/auth/dto/request/LoginRequest.java
  src/main/java/com/example/ddakdaegi/domain/auth/dto/request/RegisterRequest.java
  src/main/java/com/example/ddakdaegi/domain/member/dto/request/MemberUpdateRoleRequest.java
  src/test/java/com/example/ddakdaegi/domain/auth/service/AuthServiceTest.java
  src/test/java/com/example/ddakdaegi/domain/member/service/AdminMemberServiceTest.java
  src/test/java/com/example/ddakdaegi/domain/token/service/RefreshTokenServiceTest.java
Labels: 🛠️ infra, 🧪 test

#53 Feat/product
  src/main/java/com/example/ddakdaegi/domain/image/dto/response/ImageResponse.java
  src/main/java/com/example/ddakdaegi/domain/product/dto/response/ProductResponse.java
Labels: 🔄 refactor
